{{- if not ( or .Values.autoscaling.node .Values.autoscaling.staticRequests ) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-node-cpva
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "daemonsets"]
    verbs: ["patch"]
{{- end }}
