{{- if not ( or .Values.autoscaling.node .Values.autoscaling.staticRequests ) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node-cpva
  namespace: kube-system
automountServiceAccountToken: false
{{- end }}
