{{- if .Values.config.typha.enabled }}
{{- if not ( or .Values.autoscaling.typha .Values.autoscaling.staticRequests ) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typha-cpva
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["patch"]
{{- end }}
{{- end }}
