{{- if .Values.config.typha.enabled }}
{{- if not ( or .Values.autoscaling.typha .Values.autoscaling.staticRequests ) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: typha-cpva
  namespace: kube-system
automountServiceAccountToken: false
{{- end }}
{{- end }}
